export default interface INotesNfse {
    codeCompanie?: string,
    nameCompanie: string,
    cgceCompanie: string,
    inscricaoMunicipalCompanie: string,
    numberNote: number,
    keyNote: string,
    dateNote: Date,
    nameTomador: string,
    cgceTomador: string,
    statusNote: 'normal' | 'canceled' | 'replaced',
    amountNote: number,
    amountCalculationBase: number,
    rateISS: number,
    amountISS: number,
    amountCSLL: number,
    amountINSS: number,
    amountIRRF: number,
    amountPIS: number,
    amountCOFINS: number
}